package spring.DDG;

public enum ProductType {
	
	MOTHERBOARD,
	PROCESSOR,
	SOLID_STATE_DRIVE,
	BLUE_RAY_BURNER,
	CPU_AIR_COOLER,
	SDRAM_DDR4,
	GAMING_VIDEO_CARD,
	POWER_SUPPLY_650W,
	STEEL_TOWER,
	HARD_DRIVE,
	BOOKSIZE_BAREBONE_SYSTEM,
	HDMI_CABLE,
}
